name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation (README.md, ADVANCED.md)
          required: true
        - label: This feature would benefit the broader community, not just my specific use case
          required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New cryptographic algorithm
        - New generation mode
        - Security enhancement
        - Performance improvement
        - API enhancement
        - Documentation improvement
        - DevOps / Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, when I try to...
        I experience...
        This is a problem because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        I propose adding...
        This would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      placeholder: |
        ```typescript
        import { newFeature } from '@webx/sig';
        
        const result = await newFeature({
          // ... options
        });
        ```
      render: typescript

  - type: dropdown
    id: use-case
    attributes:
      label: Use Case
      description: What's your use case?
      options:
        - Payment systems
        - API keys / Authentication
        - Session management
        - Database IDs
        - Distributed systems
        - IoT / Edge devices
        - Research / Academic
        - Other
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      placeholder: |
        - Improved security by...
        - Better performance through...
        - Easier to use because...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my project)
        - High (needed soon)
        - Medium (would be nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes?
      options:
        - label: This would require breaking changes to the API
        - label: This is backward compatible

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have ideas about implementation, share them here
      placeholder: |
        This could be implemented by...
        Key considerations:
        - ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide code samples / examples

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related issues, papers, standards, or implementations
      placeholder: |
        - NIST standard: https://...
        - Research paper: https://...
        - Similar implementation: https://...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or information
      placeholder: Screenshots, diagrams, related issues, etc.
