name: 🔒 Security Vulnerability (Public Template)
description: Public template - Use Private Security Advisories instead
title: "⚠️ DO NOT USE THIS - Report Privately"
labels: ["invalid"]
body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ STOP - Do Not Submit Security Issues Here
        
        ## This is a PUBLIC issue template
        
        Security vulnerabilities should **NEVER** be reported in public issues.
        
        ### How to Report Security Vulnerabilities:
        
        1. **GitHub Security Advisories (Recommended):**
           - Go to the "Security" tab
           - Click "Report a vulnerability"
           - Fill out the private advisory form
        
        2. **Email:**
           - Send details to: [Your security email]
           - Include: Description, steps to reproduce, impact
        
        3. **What NOT to do:**
           - ❌ Do not create public GitHub issues
           - ❌ Do not disclose in pull requests
           - ❌ Do not post in discussions
           - ❌ Do not share on social media
        
        ### What Happens Next:
        
        - We acknowledge receipt within **48 hours**
        - We investigate and provide initial assessment within **7 days**
        - We work with you to develop and test a fix
        - We coordinate public disclosure after fix is released
        
        ### Responsible Disclosure:
        
        We follow responsible disclosure practices:
        - You report privately
        - We fix the issue
        - We credit you (if desired)
        - We disclose publicly after users can update
        
        ---
        
        **Please close this issue and report privately using one of the methods above.**
        
        See [SECURITY.md](../../SECURITY.md) for full details.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I understand I should NOT use this template for security issues
          required: true
        - label: I will report security issues privately instead
          required: true
